### ISSUE TITLE
Authorization and Multi-Tenancy proposal

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/services#149]
- Memberships to an organization are represented by an `Membership`-Entity that holds a reference to one organization and one user
- All organizations, of which the user is a part of, are included by identifier and `is_admin`-Attribute in the issued ID Token. The ID Token should be extended by the following structure:
```json
{
...
  "organizations": [
    {
      "id": "6d6bff13-226b-4c96-b83c-bd3026b7985d",
      "is_admin": false
    },
    {
      "id": "3d100af4-c47a-4bbe-bd03-7cb21cd42770",
      "is_admin": true
    }
  ]
...
}
```
With that structure directly in the ID Token, we can do our basic authorization checks without the need to resolve the relations. This approach is obviously not scalable but does its job for our current use case and doesn't block anything for the future either.
- Any entity that belongs to an organization, has an `organization_id`-Attribute in the database schema.
- The current organization is called organization context and is required for almost every request to the API. The organization context is defined by [gRPC metadata](https://grpc.io/docs/what-is-grpc/core-concepts/#metadata) via the following [schema](https://github.com/grpc/grpc-web#make-a-unary-rpc-call) `organizationID: 3d100af4-c47a-4bbe-bd03-7cb21cd42770`
- Methods like `GetRooms` (returns an array of rooms) are scoped by the organization id and are __not__ responding with all/every rooms of helpwave, only rooms of the organization context are returned.

![Bildschirm­foto 2023-04-30 um 3 18 14 PM](https://user-images.githubusercontent.com/40192999/235354959-eabe4424-d3ff-495e-a926-ac180b017350.png)

```[tasklist]
### Implement proper Authorization and Multi-Tenancy
- [ ] https://github.com/helpwave/services/issues/153
- [ ] https://github.com/helpwave/services/issues/169
- [ ] https://github.com/helpwave/services/issues/173
- [ ] https://github.com/helpwave/services/issues/158
- [ ] https://github.com/helpwave/services/issues/301
```

**Comment by FoseFx** [comment]
Conversation continues in #586
