### ISSUE TITLE
Organization invites

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/services#159]
https://github.com/helpwave/helpwave/issues/40

- An invitation can only be issued by an organization admin
- Any email address can be invited to an organization
- An invitation creates an `invitation` entity
- An invitation can have the following states (see graphiz)
- A user can identify their invites by the same email address as themselves. This enables us to invite signed-up and not signed-up users
- When an invitation gets issued, the email should receive a notification about their invite. We will track this in more detail when the invite management is build up.

```[tasklist]
### Tasks
- [ ] https://github.com/helpwave/services/issues/192
- [ ] https://github.com/helpwave/services/issues/180
- [ ] https://github.com/helpwave/services/issues/175
- [ ] https://github.com/helpwave/services/issues/193
```

![Bildschirm­foto 2023-05-21 um 3 22 10 PM](https://github.com/helpwave/services/assets/40192999/4e949484-69f9-4abc-89ff-a781df0b49cf)
![graphviz (1)](https://github.com/helpwave/services/assets/40192999/56dfc610-1cf3-4086-8b95-cce60bf45cac)

**Comment by florian-sabonchi** [comment]
@MaxSchaefer i would suggest to use Pending instead of Stalled. What's your opinion

**Comment by MaxSchaefer** [comment]
> @MaxSchaefer i would suggest to use Pending instead of Stalled. What's your opinion

@florian-sabonchi pending and stalled after different meanings.

Pending: The user has not reacted yet to the invitation. Therefore, the user can accept or decline the invitation.
Stalled: The user has not reacted in a predefined period of time. Therefore, the invitation is marked has stalled. The user cannot accept or decline the invitation.

**Comment by DasProffi** [comment]
Can we close this tracking issue? All subtasks are closed or are there still missing tasks that need to be done?

**Comment by MaxSchaefer** [comment]
Thanks @florianjs for the implementation! 🎉
