### ISSUE TITLE
Task templates

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/services#200]
This issue tracks the implementation of task templates as an entity in the `task-svc`. In the following, a JSON struct of [a meeting about task templates](https://wiki.helpwave.de/s/2f6e10b9-97c9-407c-aa9c-918915ca1bbb). Right now, task templates does not relate to other tasks.

- When `ward_id` is null, the task template is a personal template.
- When `ward_id` is not null, the task template is a ward template

```json
{
  "id": "string",
  "name": "string",
  "description": "string",
  "ward_id": "string|null", // if set, this task template is on ward level
  "created_by": "string", // mostly for GetAllTaskTemplatesByUser
  "organization_id": "string",
  "subtasks": [
    {
      "id": "string",
      "name": "string",
      "done": "boolean"
    }
  ]
}
```

```[tasklist]
### Tasks
- [ ] #201
- [ ] #208
- [ ] https://github.com/helpwave/services/issues/212
- [ ] https://github.com/helpwave/services/issues/213
- [ ] https://github.com/helpwave/services/issues/214
- [ ] https://github.com/helpwave/services/issues/215
- [ ] #217
- [ ] https://github.com/helpwave/services/issues/216
- [ ] https://github.com/helpwave/services/issues/218
```

**Comment by MaxSchaefer** [comment]
@florian-sabonchi and @DasProffi the `CreateTaskTemplate` method is implemented. Let's go!

**Comment by DasProffi** [comment]
arent't methods to change the public/private status of the taskTemplate missing?
