### ISSUE TITLE
Aggregate methods

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/services#227]
This issue tracks the progress towards aggregate methods and the splitting of the task-svc into other microservices.

```[tasklist]
### Tasks
- [ ] #203
- [ ] https://github.com/helpwave/services/issues/228
- [ ] https://github.com/helpwave/services/issues/229
- [ ] https://github.com/helpwave/services/issues/230
- [ ] https://github.com/helpwave/services/issues/231
- [ ] https://github.com/helpwave/services/issues/240
- [ ] https://github.com/helpwave/services/issues/246
- [ ] https://github.com/helpwave/services/issues/269
```
