### ISSUE TITLE
Check and implement methods for organization service

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/services#283]
### Describe the chore

```[tasklist]
### [OrganizationService](https://proto.helpwave.de/#proto%2fservices%2fuser_svc%2fv1%2forganization_svc.proto)
- [ ] https://github.com/helpwave/services/issues/284
- [ ] https://github.com/helpwave/services/issues/285
- [ ] _`AddMember` should be "private"_
- [ ] Address authorization todos for every method
```
