### ISSUE TITLE
Recent wards and patients

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/services#327]
### Describe the feature

The `task-svc` should provide an endpoint to return recent wards and patients.
A ward or patient is considered "recent" if the last interaction was at most x ago. The definition of "recent" should apply separately per user.

If we not find a decent solution right now, we're implementing these endpoints by returning the last x entities for that user _ordered by an updated_at method or so_.

```[tasklist]
### Todos until implementation
- [x] Finalize the definition of "recent"
- [x] How can we keep track of "recent" entities per user?
- [ ] https://github.com/helpwave/services/issues/335
- [ ] https://github.com/helpwave/services/issues/367
- [ ] https://github.com/helpwave/services/issues/368
- [ ] https://github.com/helpwave/services/issues/370
- [ ] https://github.com/helpwave/services/issues/369
```

### How can we keep track of "recent" entities per user?

We will publish a map with a lifetime that holds these recent identifiers for some entities into our redis. 

### Why is this feature needed?

To display recent wards and patient in our UI. This enables fast navigation and shortcuts around the app.

### Additional context

https://github.com/helpwave/web/issues/538

**Comment by MaxSchaefer** [comment]
@DasProffi what do you think about the following?
> Should the frontend defines the recent entities via an endpoint?

**Comment by DasProffi** [comment]
> @DasProffi what do you think about the following?
> 
> > Should the frontend defines the recent entities via an endpoint?

This would make sense if we would allow pinning something on the dashboard, but for this I would prefer a backend solution as this could later be extended to be the base of our event logging

**Comment by MaxSchaefer** [comment]
@FoseFx would you like to own this tracking issue and working towards completion?
