### ISSUE TITLE
Property Service Tracking Issue

### ISSUE THREAD

**Issue by FoseFx** [helpwave/services#643]
### Describe the feature

Property Feature as discussed previously:
- https://github.com/helpwave/helpwave/issues/109#issuecomment-1891115038
- https://github.com/helpwave/services/issues/611
- https://github.com/helpwave/services/issues/615

### Why is this feature needed?

- [ ] CRUD Properties (as in: Schema)
- [ ] CRUD Property Values
- [ ] Property Views Pt.1
- [ ] Property Views Pt.2
- Property Sets? @MaxSchaefer
